"""Add cascade delatesocial link

Revision ID: 0cf4588af695
Revises: 94deb1fc10d6
Create Date: 2025-06-10 16:47:48.988442

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0cf4588af695"
down_revision: Union[str, None] = "94deb1fc10d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
