"""Modify cascade deleted avatar and video

Revision ID: 1e8bd5a092e5
Revises: 0cf4588af695
Create Date: 2025-06-24 15:35:40.819199

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e8bd5a092e5"
down_revision: Union[str, None] = "0cf4588af695"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
