"""12 Add friendship model

Revision ID: 57bf21cc5e25
Revises: e65a73d8501e
Create Date: 2025-07-04 16:43:28.010798

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "57bf21cc5e25"
down_revision: Union[str, None] = "e65a73d8501e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friendship_request_table",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=False),
        sa.Column("receiver_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["receiver_id"],
            ["user_table.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["user_table.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_friendship_request_table_receiver_id"),
        "friendship_request_table",
        ["receiver_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_friendship_request_table_sender_id"),
        "friendship_request_table",
        ["sender_id"],
        unique=False,
    )
    op.create_table(
        "friendship_table",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("friend_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["friend_id"],
            ["user_table.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_table.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_friendship_table_friend_id"),
        "friendship_table",
        ["friend_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_friendship_table_user_id"),
        "friendship_table",
        ["user_id"],
        unique=False,
    )
    op.drop_column("avatar_table", "updated_at")
    op.create_index(
        op.f("ix_profile_table_id"), "profile_table", ["id"], unique=False
    )
    op.drop_constraint(
        "user_table_phone_number_key", "user_table", type_="unique"
    )
    op.create_index(
        op.f("ix_user_table_id"), "user_table", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_user_table_phone_number"),
        "user_table",
        ["phone_number"],
        unique=True,
    )
    op.drop_column("video_profile_table", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "video_profile_table",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_user_table_phone_number"), table_name="user_table")
    op.drop_index(op.f("ix_user_table_id"), table_name="user_table")
    op.create_unique_constraint(
        "user_table_phone_number_key", "user_table", ["phone_number"]
    )
    op.drop_index(op.f("ix_profile_table_id"), table_name="profile_table")
    op.add_column(
        "avatar_table",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(
        op.f("ix_friendship_table_user_id"), table_name="friendship_table"
    )
    op.drop_index(
        op.f("ix_friendship_table_friend_id"), table_name="friendship_table"
    )
    op.drop_table("friendship_table")
    op.drop_index(
        op.f("ix_friendship_request_table_sender_id"),
        table_name="friendship_request_table",
    )
    op.drop_index(
        op.f("ix_friendship_request_table_receiver_id"),
        table_name="friendship_request_table",
    )
    op.drop_table("friendship_request_table")
    # ### end Alembic commands ###
