"""empty message

Revision ID: 626a3c22f2e4
Revises:
Create Date: 2025-05-15 18:33:24.636757

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "626a3c22f2e4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "area_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("area_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_table",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("firstname", sa.String(), nullable=False),
        sa.Column("lastname", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("password", sa.LargeBinary(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("valid_email", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_table(
        "region_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("region_name", sa.String(), nullable=True),
        sa.Column("area_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["area_id"], ["area_table.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "verification_table",
        sa.Column("link", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_table.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("link"),
    )
    op.create_table(
        "community_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("community_name", sa.String(), nullable=True),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["region_id"], ["region_table.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "city_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["community_id"], ["community_table.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "profile_table",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("birthday", sa.DateTime(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("area", sa.Integer(), nullable=False),
        sa.Column("region", sa.Integer(), nullable=False),
        sa.Column("community", sa.Integer(), nullable=False),
        sa.Column("city", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["area"], ["area_table.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["city"], ["city_table.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["community"], ["community_table.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["region"], ["region_table.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_table.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "avatar_table",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("avatar_url", sa.String(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["profile_table.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "social_link_table",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["profile_table.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "video_profile_table",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("video_url", sa.String(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["profile_table.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_profile_table")
    op.drop_table("social_link_table")
    op.drop_table("avatar_table")
    op.drop_table("profile_table")
    op.drop_table("city_table")
    op.drop_table("community_table")
    op.drop_table("verification_table")
    op.drop_table("region_table")
    op.drop_table("user_table")
    op.drop_table("area_table")
    # ### end Alembic commands ###
