"""Unique user in profile model

Revision ID: 7d6d59a35411
Revises: 2ef7a7ab5a8d
Create Date: 2025-05-31 14:53:42.575982

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d6d59a35411"
down_revision: Union[str, None] = "2ef7a7ab5a8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "profile_table", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profile_table", type_="unique")
    # ### end Alembic commands ###
