"""14 remove friendship relationfield, change unique link

Revision ID: 0be85d909467
Revises: 6ed9b33374ac
Create Date: 2025-07-09 22:28:56.337136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0be85d909467"
down_revision: Union[str, None] = "6ed9b33374ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "social_link_table_link_key", "social_link_table", type_="unique"
    )
    op.create_unique_constraint(
        "uq_video_per_profile", "video_profile_table", ["profile_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_video_per_profile", "video_profile_table", type_="unique"
    )
    op.create_unique_constraint(
        "social_link_table_link_key", "social_link_table", ["link"]
    )
    # ### end Alembic commands ###
