"""Changed names some variables

Revision ID: 2ef7a7ab5a8d
Revises: 8d4d1b15fa1b
Create Date: 2025-05-30 22:56:38.405090

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ef7a7ab5a8d"
down_revision: Union[str, None] = "8d4d1b15fa1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
