"""Add link type

Revision ID: 4af5757aad2f
Revises: 7d6d59a35411
Create Date: 2025-06-03 22:35:52.679876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4af5757aad2f"
down_revision: Union[str, None] = "7d6d59a35411"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    social_link_type = sa.Enum(
        "Facebook",
        "Instagram",
        "Linkedin",
        "Twitter",
        "YouTube",
        "TikTok",
        "WhatsApp",
        "Telegram",
        "Viber",
        "Signal",
        "Pinterest",
        "Reddit",
        "Website",
        name="link_type",
        create_constraint=True,
    )
    social_link_type.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "social_link_table",
        sa.Column(
            "link_type",
            social_link_type,
            nullable=False,
        ),
    )
    op.create_unique_constraint(None, "social_link_table", ["link"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "social_link_table", type_="unique")
    op.drop_column("social_link_table", "link_type")
    # ### end Alembic commands ###
