"""13 Add unique index in friend and friend request model

Revision ID: 6ed9b33374ac
Revises: 57bf21cc5e25
Create Date: 2025-07-07 22:56:27.437258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ed9b33374ac"
down_revision: Union[str, None] = "57bf21cc5e25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_sender_receiver",
        "friendship_request_table",
        ["sender_id", "receiver_id"],
    )
    op.create_unique_constraint(
        "uq_user_friend", "friendship_table", ["user_id", "friend_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_friend", "friendship_table", type_="unique")
    op.drop_constraint(
        "uq_sender_receiver", "friendship_request_table", type_="unique"
    )
    # ### end Alembic commands ###
