"""Add city_name index in CityModel

Revision ID: 8d4d1b15fa1b
Revises: 9b52bbfceab5
Create Date: 2025-05-28 22:49:40.662046

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d4d1b15fa1b"
down_revision: Union[str, None] = "9b52bbfceab5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "city_name_index", "city_table", ["city_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("city_name_index", table_name="city_table")
    # ### end Alembic commands ###
