"""Remove unique social link

Revision ID: 94deb1fc10d6
Revises: c0d74600b3cf
Create Date: 2025-06-05 21:10:08.185826

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94deb1fc10d6"
down_revision: Union[str, None] = "c0d74600b3cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "_social_link_profile_uniq", "social_link_table", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "_social_link_profile_uniq",
        "social_link_table",
        ["link_type", "link", "profile_id"],
    )
    # ### end Alembic commands ###
