"""Add unique constrain fiels in sociallink model

Revision ID: c0d74600b3cf
Revises: 4af5757aad2f
Create Date: 2025-06-05 20:38:40.786637

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0d74600b3cf"
down_revision: Union[str, None] = "4af5757aad2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "_social_link_profile_uniq",
        "social_link_table",
        ["link_type", "link", "profile_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "_social_link_profile_uniq", "social_link_table", type_="unique"
    )
    # ### end Alembic commands ###
