"""11 remove passive deletes in avatar

Revision ID: e65a73d8501e
Revises: a7c316fe5f8a
Create Date: 2025-06-27 21:24:12.176628

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e65a73d8501e"
down_revision: Union[str, None] = "a7c316fe5f8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
